services:
  calculationsapi:
    image: ${DOCKER_REGISTRY-}calculationsapi
    container_name: calculationsapi
    build:
      context: .
      dockerfile: CalculationsApi/Dockerfile
    environment:
      OTEL_SERVICE_NAME: "calculations-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://lgtm:4317"
      OTEL_METRIC_EXPORT_INTERVAL: 500 # speeds up data collection for tech test
      FRONTEND_URL: "http://localhost:53434"
    ports: 
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - lgtm

  calculations-frontend:
    container_name: calculationsfrontend
    build:
      context: CalculationsFrontend
      args:
        VITE_API_URL: https://localhost:8081 # overrites value in env file
    ports:
      - "53434:80"
    depends_on:
      - calculationsapi

  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm
    ports:
      - "3000:3000"   # Grafana UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP